sarah grubb intake
friends-library/sarah-grubb pull request #1
Opened 2019-01-02 22:02 UTC by Henderjay

This one had some unusual formatting to it. I ended up putting in a ton a small breaks between letter segments. I can explain why if you're confused.

2019-01-20 14:51 UTC, jaredh159 requested changes
Looks good.  I think all of the `[.small-break]`s was the right move -- but I also think it's telling us that we're missing a concept or two in our formatting vocabulary and styling. If it becomes clear what that is, we might want to revisit the formatting of this book, but for now, I think this is super good. 👍

The only reason I'm not merging is to discuss the possibility of breaking out those two sections into their own chapters.

2019-01-20 14:51 UTC, jaredh159 commented on life-and-letters/modernized/07-chapter-6.adoc
> +=== A Testimony of York quarterly meeting concerning Sarah Grubb, late wife of our friend Robert Grubb, of Clonmel, in Ireland.
I wonder about maybe pulling this out into it's own chapter. Thoughts? 🤔

2019-01-20 14:51 UTC, jaredh159 commented on life-and-letters/modernized/07-chapter-6.adoc
> +=== Some Remarks on Christian Discipline, as it Respects the Education of Youth.
Same with this.

2019-01-22 21:12 UTC, Henderjay commented
Not sure if you get notifications when I do a new commit on the same branch. I made these two separate chapters at the end.

2019-01-23 02:33 UTC, jaredh159 approved these changes

2019-01-23 02:33 UTC, merged